#:schema https://www.schemastore.org/treefmt.json

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.yaml", "*.md"]

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.biome]
command = "biome"
options = ["format", "--write"]
includes = ["*.js", "*.ts", "*.json"]
