name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read

jobs:
  action:
    runs-on: ubuntu-26.04
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run action
        uses: ./. # zizmor: ignore[unpinned-uses,self-repository]

  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-26.04, ubuntu-26.04-arm, macos-26]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@da72d9fd57cb3eaddec8dd579373dea7a1a6f35a # v1.68.0

      - name: Check
        run: nix flake check
