name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@0570d65d7c69d827384b0749108a291c40b67b34 # v1.44.1

      - name: Check
        run: nix flake check

  action:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Run action
        uses: spotdemo4/node-template@main # zizmor: ignore[unpinned-uses]
